test_app/config/routes.rb
Rails.application.routes.draw do
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"

  resources :books do
    member do
      get :delete
      get :details
    end
  end
end

test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

test_app/app/models/book.rb
class Book < ApplicationRecord
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

test_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_url, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_url, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def details
    @book = Book.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(
        :title,
        :author,
        :price,
        :published_date
      )
    end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/books_helper.rb
module BooksHelper
end

test_app/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book.price %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= book.published_date.to_s %>
  </p>

</div>

test_app/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :published_date, style: "display: block" %>
    <%= form.text_field :published_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

test_app/app/views/books/delete.html.erb
<div class="Books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>
    <% # url: book_path(@Book), method: 'delete' %>

    <p>Are you sure you want to permanently delete this Book?</p>
    <p>Title: <%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

<%= link_to("Back to Books", books_path, class: 'back-link') %>

test_app/app/views/books/destroy.html.erb
<!-- app/views/books/destroy.html.erb -->

<%= link_to "Destroy Book", book_path(@book), method: :delete, data: { confirm: "Are you sure you want to destroy this book?" }, class: "btn btn-danger" %>

<div id="confirmation-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirm Destruction</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to destroy this book?</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Cancel", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
        <%= link_to "Yes, I'm sure", book_path(@book), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

test_app/app/views/books/details.html.erb
<div class="Books details">
  <h2>Book Details</h2>

  <%= form_for(@book, method: 'details') do |f| %>
    <% # url: book_path(@Book), method: 'details' %>

    <p>Title: <%= @book.title %></p>

  <% end %>
</div>

<%= link_to("Back to Books", books_path, class: 'back-link') %>

test_app/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

test_app/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Edit this book", edit_book_path(book) %> 
    </p>
    <p>
      <%= link_to("details", details_book_path(book), class: 'action details')%>
    </p>
    <p><%= link_to("Delete", delete_book_path(book), class: 'action delete') %></p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

test_app/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

test_app/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>
</div>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>